/**
 * Encapsulation of the speech settings specified by the user
 */
class SpeechSettings {
    private static DEFAULT_SOUND : any = 'R';
    private static DATA_MAP : any = {

        /*
        Global sphinx maps
        (contain all words possible and their phonemes and recognition grammars)
        */
        sphinxWords :  [['REPAIR', 'R IH P EH R'], ['WEPAIW', 'W IH P EH R'], ['REPAI', 'R IH P EH'], 
                    ['MINORITY', 'M AY N AO R AH T IY'], ['MINOWITY', 'M AY N AO W AH T IY'], 
                    ['SORROW', 'S AA R OW'], ['SOWWOW', 'S AA W OW'], 
                    ['RYE', 'R AY'], ['WYE', 'W AY'], 
                    ['EXPIRE', 'IH K S P AY R'], ['EXPIWE', 'IH K S P AY W'], 
                    ['RECYCLE', 'R IY S AY K AH L'], ['WECYCLE', 'W IY S AY K AH L'], 
                    ['RAVEN', 'R EY V AH N'], ['WAVEN', 'W EY V AH N'], 
                    ['RAG', 'R AE G'], ['WAG', 'W AE G'], 
                    ['RAN', 'R AE N'], ['WAN', 'W AE N'], 
                    ['RAM', 'R AE M'], ['WAM', 'W AE M'], 
                    ['RIP', 'R IH P'], ['WIP', 'W IH P'], 
                    ['WRENCH', 'R EH N CH'], ['WWENCH', 'W EH N CH'], 
                    ['ATTIRE', 'AH T AY ER'], ['ATTIRE', 'AH T AY UH'], 
                    ['RIB', 'R IH B'], ['WIB', 'W IH B'], 
                    ['ROAD', 'R OW D'], ['WOAD', 'W OW D'], 
                    ['RAY', 'R EY'], ['WAY', 'W EY'], 
                    ['FORUM', 'F AO R AH M'], ['FOWUM', 'F AO W AH M'], 
                    ['RADIANT', 'R EY D IY AH N T'], ['WADIANT', 'W EY D IY AH N T'], 
                    ['REDUCERADIAL', ''], 
                    ['CURRENT', 'K ER AH N T'], ['CURRENT', 'K UH AH N T'], 
                    ['BEFORE', 'B IH F AO R'], ['BEFOWE', 'B IH F AO W'], 
                    ['ROOT', 'R UW T'], ['WOOT', 'W UW T'], 
                    ['AWARE', 'AH W EH R'], ['AWAWE', 'AH W EH W'], 
                    ['ADMIRE', 'AE D M AY R'], ['ADMIWE', 'AE D M AY W'], 
                    ['MATURE', 'M AH CH UH R'], ['MATUWE', 'M AH CH UH W'], 
                    ['ROSE', 'R OW Z'], ['WOSE', 'W OW Z'], ['RICE', 'R AY S'], 
                    ['WICE', 'W AY S'], ['MEMOIR', 'M EH M W AA R'], 
                    ['MEMOIW', 'M EH M W AA W'], ['MEMOI', 'M EH M W AA'], 
                    ['JUROR', 'JH UH R ER'], ['JUWOW', 'JH UH W ER'], ['JUROR', 'JH UH R UH'], ['JURO', 'JH UH R'], 
                    ['INDOOR', 'IH N D AO R'], ['INDOOW', 'IH N D AO W'], ['INDOO', 'IH N D AO'], 
                    ['DIRECT', 'D ER EH K T'], ['DIRECT', 'D UH EH K T'], 
                    ['CARROT', 'K AE R AH T'], ['CAWWOT', 'K AE W AH T'], 
                    ['RUSH', 'R AH SH'], ['WUSH', 'W AH SH'], 
                    ['RIDE', 'R AY D'], ['WIDE', 'W AY D'], 
                    ['ROD', 'R AA D'], ['WOD', 'W AA D'], 
                    ['ROPE', 'R OW P'], ['WOPE', 'W OW P'], 
                    ['ROY', 'R OY'], ['WOY', 'W OY'], 
                    ['ANYWHERE', 'EH N IY W EH R'], ['ANYWHEWE', 'EH N IY W EH W'], 
                    ['WRIST', 'R IH S T'], ['WWIST', 'W IH S T'], 
                    ['ROT', 'R AA T'], ['WOT', 'W AA T'], 
                    ['RUST', 'R AH S T'], ['WUST', 'W AH S T'], 
                    ['ROW', 'R OW'], ['WOW', 'W OW'], 
                    ['RECITAL', 'R AH S AY T AH L'], ['WECITAL', 'W AH S AY T AH L'], 
                    ['MILLIONAIRE', 'M IH L Y AH N EH R'], ['MILLIONAIWE', 'M IH L Y AH N EH W'], 
                    ['REASON', 'R IY Z AH N'], ['WEASON', 'W IY Z AH N'], 
                    ['DAIRY', 'D EH R IY'], ['DAIWY', 'D EH W IY'], 
                    ['REST', 'R EH S T'], ['WEST', 'W EH S T'], 
                    ['READING', 'R IY D IH NG'], ['WEADING', 'W IY D IH NG'], 
                    ['IMPAIR', 'IH M P EH R'], ['IMPAIW', 'IH M P EH W'], ['IMPAI', 'IH M P EH'], 
                    ['ERODE', 'IH R OW D'], ['EWODE', 'IH W OW D'], 
                    ['RAMBLE', 'R AE M B AH L'], ['WAMBLE', 'W AE M B AH L'], 
                    ['MALARIA', 'M AH L EH R IY AH'], ['MALAWIA', 'M AH L EH W IY AH'], 
                    ['CAREER', 'K ER IH R'], ['CAWEEW', 'K ER IH W'], ['CAREUH', 'K UH IH R'], ['CAREE', 'K ER IH'], 
                    ['ACQUIRE', 'AH K W AY ER'], ['ACQUIRE', 'AH K W AY UH'], 
                    ['EVAPORATE', 'IH V AE P ER EY T'], ['EVAPORATE', 'IH V AE P UH EY T'], 
                    ['EARRING', 'IH R IH NG'], ['EAWWING', 'IH W IH NG'], 
                    ['SECONDARY', 'S EH K AH N D EH R IY'], ['SECONDAWY', 'S EH K AH N D EH W IY'], 
                    ['REAL', 'R IY L'], ['WEAL', 'W IY L'], 
                    ['BARRON', 'B AE R AH N'], ['BAWWON', 'B AE W AH N'], 
                    ['READ', 'R EH D'], ['WEAD', 'W EH D'], 
                    ['FLURRY', 'F L ER IY'], ['FLURRY', 'F L UH IY'], 
                    ['ARID', 'AE R AH D'], ['AWID', 'AE W AH D'], 
                    ['RABBIT', 'R AE B AH T'], ['WABBIT', 'W AE B AH T'], 
                    ['RING', 'R IH NG'], ['WING', 'W IH NG'], 
                    ['RED', 'R EH D'], ['WED', 'W EH D'], 
                    ['SPARROW', 'S P EH R OW'], ['SPAWWOW', 'S P EH W OW'], 
                    ['RADICAL', 'R AE D IH K AH L'], ['WADICAL', 'W AE D IH K AH L'], 
                    ['RULE', 'R UW L'], ['WULE', 'W UW L'],
                    ['CAVALIER', 'K AE V AH L IH R'], ['CAVALIEW', 'K AE V AH L IH W'], ['CAVALIE', 'K AE V AH L IH'],
                    ['ARRIVE', 'ER AY V'], ['ARRIVE', 'UH AY V'],
                    ['RAFFLE', 'R AE F AH L'], ['WAFFLE', 'W AE F AH L'], 
                    ['WELFARE', 'W EH L F EH R'], ['WELFAWE', 'W EH L F EH W'], 
                    ['ROAM', 'R OW M'], ['WOAM', 'W OW M'], 
                    ['WRITE', 'R AY T'], ['WWITE', 'W AY T'], 
                    ['RENT', 'R EH N T'], ['WENT', 'W EH N T'], 
                    ['RACCOON', 'R AE K UW N'], ['WACCOON', 'W AE K UW N'], 
                    ['RAILWAY', 'R EY L W EY'], ['WAILWAY', 'W EY L W EY'], 
                    ['AMERICA', 'AH M EH R IH K AH'], ['AMEWICA', 'AH M EH W IH K AH'], 
                    ['RUN', 'R AH N'], ['WUN', 'W AH N'], ['APPEAR', 'AH P IH R'], 
                    ['APPEAW', 'AH P IH W'], ['APPEA', 'AH P IH'], 
                    ['RABBI', 'R AE B AY'], ['WABBI', 'W AE B AY'], 
                    ['WRONG', 'R AO NG'], ['WWONG', 'W AO NG'], 
                    ['DISAPPEAR', 'D IH S AH P IH R'], ['DISAPPEAW', 'D IH S AH P IH W'], ['DISAPPEA', 'D IH S AH P IH'], 
                    ['RAFT', 'R AE F T'], ['WAFT', 'W AE F T'], 
                    ['EVERYBODY', 'EH V R IY B AA D IY'], ['EVEWYBODY', 'EH V W IY B AA D IY'], 
                    ['SECURE', 'S IH K Y UH R'], ['SECUWE', 'S IH K Y UH W'], 
                    ['RIPE', 'R AY P'], ['WIPE', 'W AY P'], 
                    ['TARTER', 'T AA R T ER'], ['TAWTEW', 'T AA W T ER'], ['TARTUH', 'T AA R T UH'], ['TARTE', 'T AA R T'], 
                    ['MATERIAL', 'M AH T IH R IY AH L'], ['MATEWIAL', 'M AH T IH W IY AH L'], 
                    ['WRAP', 'R AE P'], ['WWAP', 'W AE P'], 
                    ['EMPIRE', 'EH M P AY ER'], ['EMPIRE', 'EH M P AY UH'], 
                    ['DESIRE', 'D IH Z AY ER'], ['DESIRE', 'D IH Z AY UH'], 
                    ['REACTION', 'R IY AE K SH AH N'], ['WEACTION', 'W IY AE K SH AH N'], 
                    ['RACE', 'R EY S'], ['WACE', 'W EY S'], 
                    ['ROCK', 'R AA K'], ['WOCK', 'W AA K'], 
                    ['OPERATION', 'AA P ER EY SH AH N'], ['OPUHATION', 'AA P UH EY SH AH N'], 
                    ['INSECURE', 'IH N S AH K Y ER'], ['INSECURE', 'IH N S AH K Y UH'], 
                    ['SOFTWARE', 'S AO F T W EH R'], ['SOFTWAWE', 'S AO F T W EH W'], 
                    ['RAINBOW', 'R EY N B OW'], ['WAINBOW', 'W EY N B OW'], 
                    ['RAKE', 'R EY K'], ['WAKE', 'W EY K'], 
                    ['RAIN', 'R EY N'], ['WAIN', 'W EY N'], 
                    ['AMARILLO', 'AE M ER IH L OW'], ['AMARILLO', 'AE M UH IH L OW'], 
                    ['GUITAR', 'G IH T AA R'], ['GUITAW', 'G IH T AA W'], ['GUITA', 'G IH T AA'], 
                    ['REMEDY', 'R EH M AH D IY'], ['WEMEDY', 'W EH M AH D IY'], 
                    ['ARTIFICIAL', 'AA R T AH F IH SH AH L'], ['AWTIFICIAL', 'AA W T AH F IH SH AH L'], 
                    ['RIDER', 'R AY D ER'], ['WIDEW', 'W AY D ER'], ['RIDUH', 'R AY D UH'], ['RIDE', 'R AY D'], 
                    ['SATYR', ''], ['SATY', ''], 
                    ['COMPARE', 'K AH M P EH R'], ['COMPAWE', 'K AH M P EH W'], 
                    ['ARISE', 'ER AY Z'], ['ARISE', 'UH AY Z'], 
                    ['SINCERE', 'S IH N S IH R'], ['SINCEWE', 'S IH N S IH W'], 
                    ['GARAGE', 'G ER AA ZH'], ['GARAGE', 'G UH AA ZH'], 
                    ['RACING', 'R EY S IH NG'], ['WACING', 'W EY S IH NG'], 
                    ['AIRY', 'EH R IY'], ['AIWY', 'EH W IY'], 
                    ['RUTH', 'R UW TH'], ['WUTH', 'W UW TH'], 
                    ['ROLL', 'R OW L'], ['WOLL', 'W OW L'], 
                    ['RETIRE', 'R IH T AY R'], ['WETIWE', 'W IH T AY R'], 
                    ['BERRY', 'B EH R IY'], ['BEWWY', 'B EH W IY']]

        sphinxGrammars :  [{'word': 'REPAIR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REPAIR'}, {'to': 1, 'from': 0, 'word': 'WEPAIW'}, {'to': 1, 'from': 0, 'word': 'REPAI'}], 'end': 1, 'numStates': 3}},
                            {'word': 'MINORITY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MINORITY'}, {'to': 1, 'from': 0, 'word': 'MINOWITY'}], 'end': 1, 'numStates': 2}},
                            {'word': 'SORROW', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SORROW'}, {'to': 1, 'from': 0, 'word': 'SOWWOW'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RYE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RYE'}, {'to': 1, 'from': 0, 'word': 'WYE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'EXPIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'EXPIRE'}, {'to': 1, 'from': 0, 'word': 'EXPIWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RECYCLE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RECYCLE'}, {'to': 1, 'from': 0, 'word': 'WECYCLE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAVEN', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAVEN'}, {'to': 1, 'from': 0, 'word': 'WAVEN'}], 'end': 1, 'numStates': 2}},
                            {'word': 'RAG', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAG'}, {'to': 1, 'from': 0, 'word': 'WAG'}], 'end': 1, 'numStates': 2}},
                            {'word': 'RAN', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAN'}, {'to': 1, 'from': 0, 'word': 'WAN'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAM', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAM'}, {'to': 1, 'from': 0, 'word': 'WAM'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RIP', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RIP'}, {'to': 1, 'from': 0, 'word': 'WIP'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WRENCH', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WRENCH'}, {'to': 1, 'from': 0, 'word': 'WWENCH'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ATTIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ATTIRE'}, {'to': 1, 'from': 0, 'word': 'ATTIRE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RIB', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RIB'}, {'to': 1, 'from': 0, 'word': 'WIB'}], 'end': 1, 'numStates': 2}},
                            {'word': 'ROAD', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROAD'}, {'to': 1, 'from': 0, 'word': 'WOAD'}], 'end': 1, 'numStates': 2}},
                            {'word': 'RAY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAY'}, {'to': 1, 'from': 0, 'word': 'WAY'}], 'end': 1, 'numStates': 2}},
                            {'word': 'FORUM', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'FORUM'}, {'to': 1, 'from': 0, 'word': 'FOWUM'}], 'end': 1, 'numStates': 2}},
                            {'word': 'RADIANT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RADIANT'}, {'to': 1, 'from': 0, 'word': 'WADIANT'}], 'end': 1, 'numStates': 2}},
                            {'word': 'REDUCERADIAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REDUCERADIAL'}], 'end': 1, 'numStates': 1}},
                            {'word': 'CURRENT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'CURRENT'}, {'to': 1, 'from': 0, 'word': 'CURRENT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'BEFORE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'BEFORE'}, {'to': 1, 'from': 0, 'word': 'BEFOWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROOT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROOT'}, {'to': 1, 'from': 0, 'word': 'WOOT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'AWARE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'AWARE'}, {'to': 1, 'from': 0, 'word': 'AWAWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ADMIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ADMIRE'}, {'to': 1, 'from': 0, 'word': 'ADMIWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'MATURE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MATURE'}, {'to': 1, 'from': 0, 'word': 'MATUWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROSE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROSE'}, {'to': 1, 'from': 0, 'word': 'WOSE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RICE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RICE'}, {'to': 1, 'from': 0, 'word': 'WICE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'MEMOIR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MEMOIR'}, {'to': 1, 'from': 0, 'word': 'MEMOIW'}, {'to': 1, 'from': 0, 'word': 'MEMOI'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'JUROR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'JUROR'}, {'to': 1, 'from': 0, 'word': 'JUWOW'}, {'to': 1, 'from': 0, 'word': 'JUROR'}, {'to': 1, 'from': 0, 'word': 'JURO'}], 'end': 1, 'numStates': 4}}, 
                            {'word': 'INDOOR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'INDOOR'}, {'to': 1, 'from': 0, 'word': 'INDOOW'}, {'to': 1, 'from': 0, 'word': 'INDOO'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'DIRECT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'DIRECT'}, {'to': 1, 'from': 0, 'word': 'DIRECT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'CARROT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'CARROT'}, {'to': 1, 'from': 0, 'word': 'CAWWOT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RUSH', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RUSH'}, {'to': 1, 'from': 0, 'word': 'WUSH'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RIDE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RIDE'}, {'to': 1, 'from': 0, 'word': 'WIDE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROD', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROD'}, {'to': 1, 'from': 0, 'word': 'WOD'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROPE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROPE'}, {'to': 1, 'from': 0, 'word': 'WOPE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROY'}, {'to': 1, 'from': 0, 'word': 'WOY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ANYWHERE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ANYWHERE'}, {'to': 1, 'from': 0, 'word': 'ANYWHEWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WRIST', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WRIST'}, {'to': 1, 'from': 0, 'word': 'WWIST'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROT'}, {'to': 1, 'from': 0, 'word': 'WOT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RUST', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RUST'}, {'to': 1, 'from': 0, 'word': 'WUST'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROW', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROW'}, {'to': 1, 'from': 0, 'word': 'WOW'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RECITAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RECITAL'}, {'to': 1, 'from': 0, 'word': 'WECITAL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'MILLIONAIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MILLIONAIRE'}, {'to': 1, 'from': 0, 'word': 'MILLIONAIWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'REASON', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REASON'}, {'to': 1, 'from': 0, 'word': 'WEASON'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'DAIRY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'DAIRY'}, {'to': 1, 'from': 0, 'word': 'DAIWY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'REST', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REST'}, {'to': 1, 'from': 0, 'word': 'WEST'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'READING', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'READING'}, {'to': 1, 'from': 0, 'word': 'WEADING'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'IMPAIR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'IMPAIR'}, {'to': 1, 'from': 0, 'word': 'IMPAIW'}, {'to': 1, 'from': 0, 'word': 'IMPAI'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'ERODE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ERODE'}, {'to': 1, 'from': 0, 'word': 'EWODE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAMBLE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAMBLE'}, {'to': 1, 'from': 0, 'word': 'WAMBLE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'MALARIA', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MALARIA'}, {'to': 1, 'from': 0, 'word': 'MALAWIA'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'CAREER', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'CAREER'}, {'to': 1, 'from': 0, 'word': 'CAWEEW'}, {'to': 1, 'from': 0, 'word': 'CAREUH'}, {'to': 1, 'from': 0, 'word': 'CAREE'}], 'end': 1, 'numStates': 4}}, 
                            {'word': 'ACQUIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ACQUIRE'}, {'to': 1, 'from': 0, 'word': 'ACQUIRE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'EVAPORATE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'EVAPORATE'}, {'to': 1, 'from': 0, 'word': 'EVAPORATE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'EARRING', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'EARRING'}, {'to': 1, 'from': 0, 'word': 'EAWWING'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'SECONDARY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SECONDARY'}, {'to': 1, 'from': 0, 'word': 'SECONDAWY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'REAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REAL'}, {'to': 1, 'from': 0, 'word': 'WEAL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'BARRON', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'BARRON'}, {'to': 1, 'from': 0, 'word': 'BAWWON'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'READ', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'READ'}, {'to': 1, 'from': 0, 'word': 'WEAD'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'FLURRY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'FLURRY'}, {'to': 1, 'from': 0, 'word': 'FLURRY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ARID', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ARID'}, {'to': 1, 'from': 0, 'word': 'AWID'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RABBIT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RABBIT'}, {'to': 1, 'from': 0, 'word': 'WABBIT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RING', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RING'}, {'to': 1, 'from': 0, 'word': 'WING'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RED', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RED'}, {'to': 1, 'from': 0, 'word': 'WED'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'SPARROW', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SPARROW'}, {'to': 1, 'from': 0, 'word': 'SPAWWOW'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RADICAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RADICAL'}, {'to': 1, 'from': 0, 'word': 'WADICAL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RULE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RULE'}, {'to': 1, 'from': 0, 'word': 'WULE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'CAVALIER', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'CAVALIER'}, {'to': 1, 'from': 0, 'word': 'CAVALIEW'}, {'to': 1, 'from': 0, 'word': 'CAVALIE'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'ARRIVE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ARRIVE'}, {'to': 1, 'from': 0, 'word': 'ARRIVE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAFFLE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAFFLE'}, {'to': 1, 'from': 0, 'word': 'WAFFLE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WELFARE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WELFARE'}, {'to': 1, 'from': 0, 'word': 'WELFAWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROAM', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROAM'}, {'to': 1, 'from': 0, 'word': 'WOAM'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WRITE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WRITE'}, {'to': 1, 'from': 0, 'word': 'WWITE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RENT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RENT'}, {'to': 1, 'from': 0, 'word': 'WENT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RACCOON', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RACCOON'}, {'to': 1, 'from': 0, 'word': 'WACCOON'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAILWAY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAILWAY'}, {'to': 1, 'from': 0, 'word': 'WAILWAY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'AMERICA', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'AMERICA'}, {'to': 1, 'from': 0, 'word': 'AMEWICA'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RUN', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RUN'}, {'to': 1, 'from': 0, 'word': 'WUN'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'APPEAR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'APPEAR'}, {'to': 1, 'from': 0, 'word': 'APPEAW'}, {'to': 1, 'from': 0, 'word': 'APPEA'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'RABBI', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RABBI'}, {'to': 1, 'from': 0, 'word': 'WABBI'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WRONG', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WRONG'}, {'to': 1, 'from': 0, 'word': 'WWONG'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'DISAPPEAR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'DISAPPEAR'}, {'to': 1, 'from': 0, 'word': 'DISAPPEAW'}, {'to': 1, 'from': 0, 'word': 'DISAPPEA'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'RAFT', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAFT'}, {'to': 1, 'from': 0, 'word': 'WAFT'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'EVERYBODY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'EVERYBODY'}, {'to': 1, 'from': 0, 'word': 'EVEWYBODY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'SECURE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SECURE'}, {'to': 1, 'from': 0, 'word': 'SECUWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RIPE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RIPE'}, {'to': 1, 'from': 0, 'word': 'WIPE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'TARTER', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'TARTER'}, {'to': 1, 'from': 0, 'word': 'TAWTEW'}, {'to': 1, 'from': 0, 'word': 'TARTUH'}, {'to': 1, 'from': 0, 'word': 'TARTE'}], 'end': 1, 'numStates': 4}}, 
                            {'word': 'MATERIAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'MATERIAL'}, {'to': 1, 'from': 0, 'word': 'MATEWIAL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'WRAP', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'WRAP'}, {'to': 1, 'from': 0, 'word': 'WWAP'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'EMPIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'EMPIRE'}, {'to': 1, 'from': 0, 'word': 'EMPIRE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'DESIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'DESIRE'}, {'to': 1, 'from': 0, 'word': 'DESIRE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'REACTION', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REACTION'}, {'to': 1, 'from': 0, 'word': 'WEACTION'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RACE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RACE'}, {'to': 1, 'from': 0, 'word': 'WACE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROCK', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROCK'}, {'to': 1, 'from': 0, 'word': 'WOCK'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'OPERATION', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'OPERATION'}, {'to': 1, 'from': 0, 'word': 'OPUHATION'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'INSECURE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'INSECURE'}, {'to': 1, 'from': 0, 'word': 'INSECURE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'SOFTWARE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SOFTWARE'}, {'to': 1, 'from': 0, 'word': 'SOFTWAWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAINBOW', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAINBOW'}, {'to': 1, 'from': 0, 'word': 'WAINBOW'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAKE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAKE'}, {'to': 1, 'from': 0, 'word': 'WAKE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RAIN', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RAIN'}, {'to': 1, 'from': 0, 'word': 'WAIN'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'AMARILLO', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'AMARILLO'}, {'to': 1, 'from': 0, 'word': 'AMARILLO'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'GUITAR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'GUITAR'}, {'to': 1, 'from': 0, 'word': 'GUITAW'}, {'to': 1, 'from': 0, 'word': 'GUITA'}], 'end': 1, 'numStates': 3}}, 
                            {'word': 'REMEDY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'REMEDY'}, {'to': 1, 'from': 0, 'word': 'WEMEDY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ARTIFICIAL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ARTIFICIAL'}, {'to': 1, 'from': 0, 'word': 'AWTIFICIAL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RIDER', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RIDER'}, {'to': 1, 'from': 0, 'word': 'WIDEW'}, {'to': 1, 'from': 0, 'word': 'RIDUH'}, {'to': 1, 'from': 0, 'word': 'RIDE'}], 'end': 1, 'numStates': 4}}, 
                            {'word': 'SATYR', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SATYR'}, {'to': 1, 'from': 0, 'word': 'SATY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'COMPARE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'COMPARE'}, {'to': 1, 'from': 0, 'word': 'COMPAWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ARISE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ARISE'}, {'to': 1, 'from': 0, 'word': 'ARISE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'SINCERE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'SINCERE'}, {'to': 1, 'from': 0, 'word': 'SINCEWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'GARAGE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'GARAGE'}, {'to': 1, 'from': 0, 'word': 'GARAGE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RACING', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RACING'}, {'to': 1, 'from': 0, 'word': 'WACING'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'AIRY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'AIRY'}, {'to': 1, 'from': 0, 'word': 'AIWY'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RUTH', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RUTH'}, {'to': 1, 'from': 0, 'word': 'WUTH'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'ROLL', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'ROLL'}, {'to': 1, 'from': 0, 'word': 'WOLL'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'RETIRE', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'RETIRE'}, {'to': 1, 'from': 0, 'word': 'WETIWE'}], 'end': 1, 'numStates': 2}}, 
                            {'word': 'BERRY', 'g': {'start': 0, 'transitions': [{'to': 1, 'from': 0, 'word': 'BERRY'}, {'to': 1, 'from': 0, 'word': 'BEWWY'}], 'end': 1, 'numStates': 2}}]

        wordBank :  [{'wrong': ['WEPAIW', 'REPAI'], 'right': 'REPAIR'}, 
                    {'wrong': ['MINOWITY'], 'right': 'MINORITY'}, 
                    {'wrong': ['SOWWOW'], 'right': 'SORROW'}, 
                    {'wrong': ['WYE'], 'right': 'RYE'}, 
                    {'wrong': ['EXPIWE'], 'right': 'EXPIRE'}, 
                    {'wrong': ['WECYCLE'], 'right': 'RECYCLE'}, 
                    {'wrong': ['WAVEN'], 'right': 'RAVEN'}, 
                    {'wrong': ['WAG'], 'right': 'RAG'}, 
                    {'wrong': ['WAN'], 'right': 'RAN'}, 
                    {'wrong': ['WAM'], 'right': 'RAM'}, 
                    {'wrong': ['WIP'], 'right': 'RIP'}, 
                    {'wrong': ['WWENCH'], 'right': 'WRENCH'}, 
                    {'wrong': ['ATTIRE'], 'right': 'ATTIRE'}, 
                    {'wrong': ['WIB'], 'right': 'RIB'}, 
                    {'wrong': ['WOAD'], 'right': 'ROAD'}, 
                    {'wrong': ['WAY'], 'right': 'RAY'}, 
                    {'wrong': ['FOWUM'], 'right': 'FORUM'}, 
                    {'wrong': ['WADIANT'], 'right': 'RADIANT'}, 
                    {'wrong': [], 'right': 'REDUCERADIAL'}, 
                    {'wrong': ['CURRENT'], 'right': 'CURRENT'}, 
                    {'wrong': ['BEFOWE'], 'right': 'BEFORE'}, 
                    {'wrong': ['WOOT'], 'right': 'ROOT'}, 
                    {'wrong': ['AWAWE'], 'right': 'AWARE'}, 
                    {'wrong': ['ADMIWE'], 'right': 'ADMIRE'}, 
                    {'wrong': ['MATUWE'], 'right': 'MATURE'}, 
                    {'wrong': ['WOSE'], 'right': 'ROSE'}, 
                    {'wrong': ['WICE'], 'right': 'RICE'}, 
                    {'wrong': ['MEMOIW', 'MEMOI'], 'right': 'MEMOIR'}, 
                    {'wrong': ['JUWOW', 'JUROR', 'JURO'], 'right': 'JUROR'}, 
                    {'wrong': ['INDOOW', 'INDOO'], 'right': 'INDOOR'}, 
                    {'wrong': ['DIRECT'], 'right': 'DIRECT'}, 
                    {'wrong': ['CAWWOT'], 'right': 'CARROT'}, 
                    {'wrong': ['WUSH'], 'right': 'RUSH'}, 
                    {'wrong': ['WIDE'], 'right': 'RIDE'}, 
                    {'wrong': ['WOD'], 'right': 'ROD'}, 
                    {'wrong': ['WOPE'], 'right': 'ROPE'}, 
                    {'wrong': ['WOY'], 'right': 'ROY'}, 
                    {'wrong': ['ANYWHEWE'], 'right': 'ANYWHERE'}, 
                    {'wrong': ['WWIST'], 'right': 'WRIST'}, 
                    {'wrong': ['WOT'], 'right': 'ROT'},
                    {'wrong': ['WUST'], 'right': 'RUST'}, 
                    {'wrong': ['WOW'], 'right': 'ROW'}, 
                    {'wrong': ['WECITAL'], 'right': 'RECITAL'}, 
                    {'wrong': ['MILLIONAIWE'], 'right': 'MILLIONAIRE'}, 
                    {'wrong': ['WEASON'], 'right': 'REASON'}, 
                    {'wrong': ['DAIWY'], 'right': 'DAIRY'}, 
                    {'wrong': ['WEST'], 'right': 'REST'},
                    {'wrong': ['WEADING'], 'right': 'READING'}, 
                    {'wrong': ['IMPAIW', 'IMPAI'], 'right': 'IMPAIR'}, 
                    {'wrong': ['EWODE'], 'right': 'ERODE'}, 
                    {'wrong': ['WAMBLE'], 'right': 'RAMBLE'}, 
                    {'wrong': ['MALAWIA'], 'right': 'MALARIA'}, 
                    {'wrong': ['CAWEEW', 'CAREUH', 'CAREE'], 'right': 'CAREER'}, 
                    {'wrong': ['ACQUIRE'], 'right': 'ACQUIRE'}, 
                    {'wrong': ['EVAPORATE'], 'right': 'EVAPORATE'}, 
                    {'wrong': ['EAWWING'], 'right': 'EARRING'}, 
                    {'wrong': ['SECONDAWY'], 'right': 'SECONDARY'}, 
                    {'wrong': ['WEAL'], 'right': 'REAL'}, 
                    {'wrong': ['BAWWON'], 'right': 'BARRON'}, 
                    {'wrong': ['WEAD'], 'right': 'READ'}, 
                    {'wrong': ['FLURRY'], 'right': 'FLURRY'}, 
                    {'wrong': ['AWID'], 'right': 'ARID'}, 
                    {'wrong': ['WABBIT'], 'right': 'RABBIT'}, 
                    {'wrong': ['WING'], 'right': 'RING'}, 
                    {'wrong': ['WED'], 'right': 'RED'}, 
                    {'wrong': ['SPAWWOW'], 'right': 'SPARROW'}, 
                    {'wrong': ['WADICAL'], 'right': 'RADICAL'}, 
                    {'wrong': ['WULE'], 'right': 'RULE'}, 
                    {'wrong': ['CAVALIEW', 'CAVALIE'], 'right': 'CAVALIER'}, 
                    {'wrong': ['ARRIVE'], 'right': 'ARRIVE'}, 
                    {'wrong': ['WAFFLE'], 'right': 'RAFFLE'}, 
                    {'wrong': ['WELFAWE'], 'right': 'WELFARE'}, 
                    {'wrong': ['WOAM'], 'right': 'ROAM'}, 
                    {'wrong': ['WWITE'], 'right': 'WRITE'}, 
                    {'wrong': ['WENT'], 'right': 'RENT'}, 
                    {'wrong': ['WACCOON'], 'right': 'RACCOON'}, 
                    {'wrong': ['WAILWAY'], 'right': 'RAILWAY'}, 
                    {'wrong': ['AMEWICA'], 'right': 'AMERICA'}, 
                    {'wrong': ['WUN'], 'right': 'RUN'}, 
                    {'wrong': ['APPEAW', 'APPEA'], 'right': 'APPEAR'}, 
                    {'wrong': ['WABBI'], 'right': 'RABBI'}, 
                    {'wrong': ['WWONG'], 'right': 'WRONG'}, 
                    {'wrong': ['DISAPPEAW', 'DISAPPEA'], 'right': 'DISAPPEAR'}, 
                    {'wrong': ['WAFT'], 'right': 'RAFT'}, 
                    {'wrong': ['EVEWYBODY'], 'right': 'EVERYBODY'}, 
                    {'wrong': ['SECUWE'], 'right': 'SECURE'}, 
                    {'wrong': ['WIPE'], 'right': 'RIPE'}, 
                    {'wrong': ['TAWTEW', 'TARTUH', 'TARTE'], 'right': 'TARTER'}, 
                    {'wrong': ['MATEWIAL'], 'right': 'MATERIAL'}, 
                    {'wrong': ['WWAP'], 'right': 'WRAP'}, 
                    {'wrong': ['EMPIRE'], 'right': 'EMPIRE'}, 
                    {'wrong': ['DESIRE'], 'right': 'DESIRE'}, 
                    {'wrong': ['WEACTION'], 'right': 'REACTION'}, 
                    {'wrong': ['WACE'], 'right': 'RACE'}, 
                    {'wrong': ['WOCK'], 'right': 'ROCK'}, 
                    {'wrong': ['OPUHATION'], 'right': 'OPERATION'}, 
                    {'wrong': ['INSECURE'], 'right': 'INSECURE'}, 
                    {'wrong': ['SOFTWAWE'], 'right': 'SOFTWARE'}, 
                    {'wrong': ['WAINBOW'], 'right': 'RAINBOW'}, 
                    {'wrong': ['WAKE'], 'right': 'RAKE'}, 
                    {'wrong': ['WAIN'], 'right': 'RAIN'}, 
                    {'wrong': ['AMARILLO'], 'right': 'AMARILLO'}, 
                    {'wrong': ['GUITAW', 'GUITA'], 'right': 'GUITAR'}, 
                    {'wrong': ['WEMEDY'], 'right': 'REMEDY'}, 
                    {'wrong': ['AWTIFICIAL'], 'right': 'ARTIFICIAL'}, 
                    {'wrong': ['WIDEW', 'RIDUH', 'RIDE'], 'right': 'RIDER'}, 
                    {'wrong': ['SATY'], 'right': 'SATYR'}, 
                    {'wrong': ['COMPAWE'], 'right': 'COMPARE'}, 
                    {'wrong': ['ARISE'], 'right': 'ARISE'}, 
                    {'wrong': ['SINCEWE'], 'right': 'SINCERE'}, 
                    {'wrong': ['GARAGE'], 'right': 'GARAGE'}, 
                    {'wrong': ['WACING'], 'right': 'RACING'}, 
                    {'wrong': ['AIWY'], 'right': 'AIRY'}, 
                    {'wrong': ['WUTH'], 'right': 'RUTH'}, 
                    {'wrong': ['WOLL'], 'right': 'ROLL'}, 
                    {'wrong': ['WETIWE'], 'right': 'RETIRE'}, 
                    {'wrong': ['BEWWY'], 'right': 'BERRY'}]

    };

    private wordBank : string[];

    constructor() {
        this.setSound(SpeechSettings.DEFAULT_SOUND);
    }

    /**
     * Sets a particular problem area sound to work on
     * @param soundType The sound type to work on
     */
    public setSound(soundType : string) {
        var dataBank = SpeechSettings.DATA_MAP[soundType];

        // set state of the settings to the data
        this.wordBank = dataBank.wordBank;
    }

    /**
     * Get the map of sphinx grammars
     * @returns {any} The sphinx grammars
     */
    public getSphinxGrammars() {
        return SpeechSettings.DATA_MAP.sphinxGrammars;
    }

    /**
     * Get the map of sphinx words
     * @returns {any} The sphinx grammars
     */
    public getSphinxWords() {
        return SpeechSettings.DATA_MAP.sphinxWords;
    }

    /**
     * Gets the current bank of words
     * @param level the word bank level
     * @returns {string[]} The bank of words
     */
    public getWordBank() {
        return this.wordBank;
    }
}

export = SpeechSettings;